import type { Metadata } from "next";
import "./globals.css";
import { Noto } from "../font";
import { worker } from "@/__mocks__/browser";

if (process.env.NODE_ENV === "development") {
  worker.start();
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      {/* <link href="./output.css" rel="stylesheet" /> */}
      <body className={Noto.variable + " font"}>{children}</body>
    </html>
  );
}
