import type { Metadata } from "next";
import "./globals.css";
import { Noto_Sans_KR } from "next/font/google";
import { worker } from "@/__mocks__/browser";

const noto = Noto_Sans_KR({ subsets: ["latin"] });

if (process.env.NODE_ENV === "development") {
  worker.start();
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${noto.className}  antialiased`}>{children}</body>
    </html>
  );
}
